baseURL = 'https://andrewmoores.dev/'
languageCode = 'en-uk'
title = 'Andrew Moores Blog'
theme = 'xmin'
enableRobotsTXT = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "GitHub"
url = "https://github.com/asmoores"
weight = 4

paginate = 5
paginatePath = "page"

[params]
description = "Andrew Moores Blog - Thoughts on technology, development, and productivity tools including Hugo, Claude Code, Obsidian, and software engineering best practices"
customCSS = ["/css/custom-styles.css"]
googleAnalytics = "G-5W3XXPNZNE"