baseURL = 'https://andrewmoores.dev/'
languageCode = 'en-uk'
title = 'Andrew Moores Blog'
theme = 'xmin'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

paginate = 5
paginatePath = "page"

[params]
description = "Andrew Moores Blog - Thoughts on technology, development, and productivity tools including Hugo, Claude Code, Obsidian, and software engineering best practices"
customCSS = ["/css/custom-styles.css"]
# googleAnalytics = "G-XXXXXXXXXX"  # Replace with your Google Analytics 4 Measurement ID